[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "9ab9436142df4326e0772ce04d7fed9f74e089f1"
libgfortran_version = "5.0.0"
os = "macos"

    [[L_BFGS_B.download]]
    sha256 = "d88b5d01ff154a9aa89568bfb0c7e1489789f1d4a63dd6fefffca5042e5df5ab"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "3889c106a1eeb452c0002c97d2088c6ded268caa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "be98f4fd094dce1006d27f9a50c91610640cc1baea33b413e4150e9869e0c160"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "153eeb8fb10066a79678f59f9704bf0bed23aeb6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "4aff3e54e339c3c921f9e7251c129044ecec5fa2ffcfc4e21df8e120b7239397"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "69e47a79b130126b41f5108c03caf9c9a59ea616"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "37c0a1a677f3bc23ab1d951b25130e1c2a459271147dfcee3adf447e5d8561f0"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "9b26c095e53fec0635a2a27f5d309bf9e370ef76"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "bf4bd95912d4c158fd3474d940ecf6564f2a691d5117d103ce78d88f2d6d74d7"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "e9c37c4c0ddc979d6784e8d6bb07e6bb3a1bd6f7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "3fad5dd07517e1372bab756e47bef5af6092e0bd453a429a951cfe08c445e9c4"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "05ae9424b2088b31fa9e558efa4ee98aac98585e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "1d1167e34a5aa0102d8010d4aab8b3f73d9c73ae208ff8ff1692a6bc79133a1e"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b45d85873141b1042945146dab924860e95e584"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "c66239de7d322f530924ba4f878fcecffe6008fc40230d71219566e2bfcf8899"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "88152d0b15d8bf31b1412ae594fd66e0fb0b1913"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "f471ac8241743d5100cb157be6c4f648c4365dca5de2a600a8a97c62ee1dae52"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9ee283b51375f805571dd99bdb4221f3eb7a3222"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "694177ee3bedc4a659f0b49ba898e9a084da9c5904d6aea465764c2e3fea8352"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d516da06b06f5afb016200da8dc7ba23ff73b598"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "1daffbda9ec0dae15cbd3590fd5c870dafc240482de441ebd7be14474b513f70"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d9359dfb1b19ea5dcf5481d5342f9fbcf50146d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "b7fb7c1df260640c54ba6d12e1c76dcff5cae72c75a6e5bc6087620110db9f8c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21430238c2d0915ef2f130aa4180ec0236762aff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "406e9520648af354c115d7242a3e32b0955e6af23fea3ad98b1d163f941e5bc4"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92bfe1a954ebebd7dbde3c13624292c7d7d796e9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "9f004194cebbb507ea6cf02d21359db86c4d30d3a2a4b566e4a44102a76c5919"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f870fe3ee8c463f098ee0e96c812624f887352e1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "6478549a1bf7647b43b2cfc67ce48575ca7623784173e9cd6de3408dd528660c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98d4474189504832a34ebc2f4eab9555386acb39"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "a6fef83db47aa1015b2c01fe4af1f5d6a7f37ad2507853676d44c55917ab27a3"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "66e6b09782057f3b85286f6f498f49c5946ff1e6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "ce286126fa5f2b2a981635ba1f0054aedc2caa374fb02678d3884b047d46c158"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9ff792730c00cab3e163e7fe743f065d1385e31"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "eccb6783449607e9ac6363c12210662811514ff7dcd2bbf176de534488392efc"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d29e9593f1c48ad8b45b53b29aee01f0d8d3f6f8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "99f2598236587b8f73cd980cd2eecd30f4e097d4d983b34a204bb93009095964"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "5e0619a34e139cdb88cd485b14a2c93f93d5a9a4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "8a897a5cae16418ec5e54303fb202b26da71cdd1a6e90215225f54d90a23952e"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "1024259b71efe8634f628b70508af48d960514b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "4768a7309a634d97b9eed1b9e7e84191e2bfbf2e3905edc59f38e3008377ec1c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "cda9e23cbd66b6c1cc4fa16df6bae1cc0112151f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "db76b8b8d6a5f6359cc88a8afaf8d7ed70bdc286304b4b5d1bc99600516a0f5d"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "2921da57634c16a75563f4af55c20368013b30c6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "bdef898cd49febf19656ad995b11584ec66523d13bd464d0fd723e4ba964c78c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-linux-musl-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "7b5e0e784895a275ec8b1d542250d863e50803b6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "c396049776f196176b0aae40b82715200fc122f34ca353712deb959eddc430ac"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "671b94ec8c24be100242d537297e0876a768a660"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "a43d96d5cc18a205cffa36956fa546e8d32d626186af56b14b7af55f9c0b669d"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "5438a9a824f9d8c68dd9eb8b36be48153f37d877"
libgfortran_version = "3.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "08dc297f25a289c841a1fef05bf43299827d0a4af0810f5c3cd160f4f91a91d7"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "ae986c0c42c9a03f7709d08c69cc5a472ef7968d"
libgfortran_version = "4.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "e48716c16eb7d7b8be8a1dbc4b54befb18de7f7538b227c596b770012064ac4c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "dd6d4455736dbed66495cea6234619e93476ed9c"
libgfortran_version = "5.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "bf9c5607fde2cec11ead520a23c6c4c08b82e7b11939ae4377823542977c91a8"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "powerpc64le"
git-tree-sha1 = "4ea8fe552fec2ddabc1868ef7888b846b65e8a82"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "76ddc6a02f726cd258f7320c1bf728546c61de71ced538a6d0b11fe50763d374"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "powerpc64le"
git-tree-sha1 = "742c95d0d854fb91bcf86b522a699850eb5da3d1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "0cb4254e27105d51c156f5aa446c6242346e5da264129137d11325df749d1fa5"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "powerpc64le"
git-tree-sha1 = "974f59cbfa702f066ff5d8ae6d6cfe5289b2268e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "00372cea673f92712f3b9e8df08425549d7d35b003c9729e6198ac7be0ec45b2"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "1e4baccd765b6575c876ee127ba6285efb51661f"
libgfortran_version = "3.0.0"
os = "macos"

    [[L_BFGS_B.download]]
    sha256 = "7674d5ced592f5db64f928cf3998446a675c007b671a353bd90606a423a66137"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "2d72d5cb6b1b0b13c6b993d967db32ed33e994af"
libgfortran_version = "4.0.0"
os = "macos"

    [[L_BFGS_B.download]]
    sha256 = "e68a5a28fdd32187c28c3081b06f388f9714e7ba552bb20e23e9def4959c05f3"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "1697c85a0eec28d5a450f5055c24ac2764026944"
libgfortran_version = "5.0.0"
os = "macos"

    [[L_BFGS_B.download]]
    sha256 = "a1e67e6a84ae7080cca9cc3f1d503faf5081741ead32259197f79b29a42b2537"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "17379f4d37660ceab7e58e5396d1a78428702953"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "bef55df3f7e1b40ef0ace6f878c8b7fc616bcc6ecb8d9ae3eff7a68f14e2b737"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "d48dce558fb8e6c38668f66cb691a775c660e42b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "4228c2f484890a85ce45e3a6278cc4c65de997dd1dc2e808366d2f6797b03e6c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "c217359059a8dc6f507aa51e7821ea955f7408aa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "e6a9a565b5052c9ff5aed9d1adc54ebb62c9d7dde40a5f4d488159c7f282f875"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "c73ebbca43bcc3eeb5969c42f6a9c7ad69f9899a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "01048689cad92672e49aed3d56298c18c7ba5a892c879dbc60d73bdccaf61ec5"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "ac7179098dc18cde2f61cd4e3012e0689a685f13"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "17a646e2cc08dd21769f4fd786649b22b1c9117c333c664e57d1f10e68e092d6"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "abb67d8e3f83917e1b5312aea94266eea42f5e5f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "8d2f0c235a159ec5a73349a149646d2c11cf05a0af2b29258f86d6c50dc7359d"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "3bdd559b295e53c67b0b7b9a25ac7bc217da87c9"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[L_BFGS_B.download]]
    sha256 = "e1f1fe212a3dbe2ba86522c8a14e184500e7e0e76516ba6c095d6b4a74d052f7"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "770695cce2f527566252725f0b411d8db87cb7e7"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[L_BFGS_B.download]]
    sha256 = "f1cb9924a093d77e0e50116b35b4f4eb2426d5251fe6f535ed97401b4a70579c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "058cfb89cd9db5de733d65aba26772d09e1c6c5f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[L_BFGS_B.download]]
    sha256 = "4ff60cf22ce40352776cb20635c5efd6caea400942c8bf058b45b0cac7d702a5"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "bcfc063d88e30e9c4db582e22b31771162a976e2"
libgfortran_version = "3.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "617de4c0d81e1d0ad4d3ab297bbc53afcddbb3a00adf349d0da6b0960d7e6142"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "527ca9eae07bed5494a8a658fe654e33b5fd9e05"
libgfortran_version = "4.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "d16011103560521a98bcedaa00e06ea628132b7e2889833bbc55dcb98e6ee617"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "7ebc9249becc8c75e679c2be48a746cf29b92ae7"
libgfortran_version = "5.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "0597758d2b1cb76f1fb8b82e8c98b5add539582aedbca89ee0e7310d09e6a306"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.1+0/L_BFGS_B.v3.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
