[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "b3debb11c6574d0f3ab4700a6f5aa45eb16af79a"
libgfortran_version = "5.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "bb81a2ba3e1fcb54296331cc91923c6887d1ea63557fc5c0b541fe73ccd4ea94"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "03a1e5a6b91570869ef0f7b7eb0d5511a0f5bd8b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[L_BFGS_B.download]]
    sha256 = "2ab3d9dcdc2d6d9934eb7e50046276d6a14b4bcc0463faceece5827135e6cd14"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "84a0b87689c9cdd22351559644a6fd3b3cba0201"
libgfortran_version = "3.0.0"
os = "macos"

    [[L_BFGS_B.download]]
    sha256 = "bdc175f530685958f51a08c8c5332736239274b7d7d86075cc0273eb1d01914c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "4d583eae1b069be74a22c6e6a19f182f0470c132"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "4b119dd125db487eb4e3e153326e0ff6044f778dbd0b91152c63e237ea62ad54"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "17d57fbf8e2bdbddf1c6e101b26f6a8249ffdd0d"
libgfortran_version = "4.0.0"
os = "macos"

    [[L_BFGS_B.download]]
    sha256 = "99af89017b7e056349382fc722f08970775849912d04587fedc9d95c888b6cc3"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "80bea6a435e7c2ed0afaccb931fc3ba63f97faf1"
libgfortran_version = "5.0.0"
os = "macos"

    [[L_BFGS_B.download]]
    sha256 = "b31d8f83a0d9aeee7a95870241839ab8738109dd2b9179d05bf7b94eb889e863"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
git-tree-sha1 = "5645689a4a6df3183885249203fdd7ee5b7e0345"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "7d87a3a4f7c3791028c0d971eaf6d388234b61e8548e2e4117c9d299967cd48f"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "a74b1f96c8f3e1266c9bbb2164298c78bbb6c38d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "06a4801f50d7ee45292083a66870e0789c147e2ea1ac15838dceb01623c4054d"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "c94d132c5ccdc31e43754b87526fe802109c3348"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "18778bb2f68645cb5c53228795c049214be32aa0a7947b78d0a61f5c3126338d"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "powerpc64le"
git-tree-sha1 = "928ea320a501906d24b5ed4b535b3b384075b1b7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "b7d15e8aad60be089be669a8e341ea7fb8b4a173114c2f3b18a18a0addb43438"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
git-tree-sha1 = "8a51f61038e8423cfe1c9cddf008eaedc31b7a44"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "ff89d262c7d0ff69b428c3935b2d44cb2340c65fabfc46348416b499afd37c72"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "893280bc39fde6fcc38259174643c4c1886bcaac"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "da5d8614c3cbfe8fb6ec9b4cbacc3361d2b0a1e49a2fbe64b1098d24375a49bf"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "powerpc64le"
git-tree-sha1 = "591782a39b9055460c019668b68a25d7e48d2cf2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "a2aee19f687e08ce24ec3370f6735e2f9a0d3eab14032b6e7016740b764c1043"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "68bf9c370d94a912ca031df0e267a0ed98446a0b"
libgfortran_version = "4.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "c659320e2c21d2fcdb4a7d676ef036f2f843c867c10870236442eead5905ccc0"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
git-tree-sha1 = "cd2412d0cd581d48b1cc830808c83dce4b167a3e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "224b16f4550a440de63cec956302408895155d773fc116eb3e93645bbe5fd2b0"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "442185a00b50ad3aabd02e72bcf192394c3810f0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "e4d4042f12556c0c5893ba7b105229a2980e9db4280495f53bc1be4eceead15c"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "a8e152c7bfa5a1120254142fd17f2c76bf16feaf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "a21da0e84b217995a26c0c9b7ab5bd821a3daa149be122a58a3856c2b08cd223"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
git-tree-sha1 = "850e4bda1aa5e30dcbb7b0d51ba415f66ae256c2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "27518458d1520f90523f4d5b888e5a0b0f5aa3744ccbd1b57d575006f4ae0807"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "55df71e816499fb061e593c927fc38c8e19c116b"
libgfortran_version = "5.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "fe4bb4af2ebb74fd90f8befc64bbc120f48e1a72af86916e8c83a2ac6d818204"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "a104038a15ba352aa964c77efb2f27f60006c316"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "68d9648e7891f3f21c3d4cd50d14c218b6393cd789e4823a058dbfe1c09c54fd"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "d9ecaed67da38f31a02ffb9ee69e29b3c24ca2f1"
libgfortran_version = "3.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "ada24a2a287d77ca34b7b6f8a2fbe70b93c95b7e6b9afe41b278a45d06577fa8"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "95bd1507c40acc870c47ee7ef0c8faa1cf5f3fa0"
libgfortran_version = "4.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "e097ad1a81a58a637992ac9b254c09e2b35bea19f33f5bbdfe88cd060b8940e8"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "c576b082876c89ebbcf56baef6f8f0dc52a9d969"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[L_BFGS_B.download]]
    sha256 = "365e890c0e37c38d4a434fddc515f05ccccdeaea22e5ffce456cd539182289a3"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "e12b522fe356203b46303d53cca47030489828c4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "ad5e231f4a445b48296a800cd0f625791f77d04addaf827979627674f50faa98"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "d07d2bef4f4e43558cc49650ded454898edacb17"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "9cd46ad03517b72d78b82c94bf49328d5e141693b5f319f3a621235dd98f2dd0"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "5955de1e85a8b12d401fec08b3e29b5a292136f8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "c1921e2b960757d728cb259625b2a9ae3b83541050eb949ac955f743cf0551e0"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "266b3c982e9b0c2e7d0b392a5a1fba6ddca36b8d"
libgfortran_version = "3.0.0"
os = "windows"

    [[L_BFGS_B.download]]
    sha256 = "75de55c7af507424add5a2f5b02d1bb75cc5537596c700a07c0235b981abae7d"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
git-tree-sha1 = "1593943844bddfd0ae3b18e07f03523b738f718f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "22db18a6c4f5e1658f2acc2e509e4aa9dcb87e558880fe09d77d247ff04c2788"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "6290866805591aa35ee101938749a386542edeca"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "102509b36467233a0001352f44578735046aa091fb29f9b3d3080157fb9026d1"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "dd1c682ed48216bdf0b8b4f981ced1d12c2ccdab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "0259f8525dc65c2014ef70ddaa774ab7944d4ad8964ef1f0e8c6facf4b6e38a8"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "af752bfd04c7a1673b837fdf539c8a9f4dcbf573"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "860714a960842674c5ccf6e92d900ae4bb481f6094a15e0c34cfa564ace96f6d"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "96b6219bc5175a5c615f0a7df5018199530df855"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "f42bf0d35eab6ad91d6aefbc0db46e382e75f267f9d1d21c868ee0ccd256b71b"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "16251e6c84bfd9c8c46db92fe8b244adccf543f3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "269f435756e7a92a2ab50f61879562958a9f09b907a2732e891b1014ff9e7249"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "x86_64"
git-tree-sha1 = "cd8dc6b7f44b725786d74746d17cdd5a9f326e2f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[L_BFGS_B.download]]
    sha256 = "6d6aa9a558e1bd5e3df9e90ba4dc52f297860c84900c7fe731348bb191fffc8b"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "0e1d7ccb898afe3885ca8c1d00a5702e2d67a73a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "7f090cd503431432dd9819bb9b05235dec03734fef805eee328fee5fa07cdf1b"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[L_BFGS_B]]
arch = "armv7l"
git-tree-sha1 = "015c844cfc5ba75c4165d6a3c61550d21bb6411d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "ae5fafc13d04ac0618d6e3dde8b0a9cb19aed179e473fd3dc94181936e77b2b8"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "i686"
git-tree-sha1 = "4f987582a0f49eafd5398056cae8277ea558db38"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "6452cb1b60bd21b74307ef267aaf2255b55bba803dba651d89719d35e895d1d7"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[L_BFGS_B]]
arch = "aarch64"
git-tree-sha1 = "5ba1d1d50d371f714c172528fc08a8ce7f96f2a1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "1dd9440d6e4aa08c2fac923da4e01f8c300de8446ade3447a258239ae2bb88f7"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[L_BFGS_B]]
arch = "powerpc64le"
git-tree-sha1 = "78f2dbd3229341b5d58057a79c589f1f64bcd93d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[L_BFGS_B.download]]
    sha256 = "547ea7c4fb120a5398d4b50196d50ffe60d8b25481f1e8def607d839908e3bed"
    url = "https://github.com/JuliaBinaryWrappers/L_BFGS_B_jll.jl/releases/download/L_BFGS_B-v3.0.0+1/L_BFGS_B.v3.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
